services:
  # Backend API
  - type: web
    name: senai-vitrine-api
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: senai-vitrine-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: senai-vitrine-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: senai-vitrine-db
          property: password
      - key: API_SECRET
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: senai-vitrine-db
    databaseName: senai_vitrine
    user: senai_user
    region: oregon
    plan: free
